const productsRouter = require('./products.route')
const productCategoriesRouter = require('./product-category.route')
const userRouter = require('./user.route')
const cartRouter = require('./cart.route')
const promoRouter = require('./promo-codes.route')
const ordersRouter = require('./order.route')
const orderTrackingRouter = require('./order-tracking.route')
const widgetsRouter = require('./widgets.route')
const bannersRouter = require('./banners.route')
const flashsalesRouter = require('./flashsales.route')
const contactRouter = require('./contact.route')
const bankInfoRouter = require('./bankInfo.route')
const reviewsRouter = require('./reviews.route')
const paymentRouter = require('./payment.route')
const wishlistRouter = require('./wishlist.route')
const chatRouter = require('./chat.route')

const authenticateToken = require('../../middlewares/client/authenticateToken.middleware')

module.exports = app => {
  const version = '/api/v1'
  app.use(version + '/products', productsRouter)
  app.use(version + '/product-categories', productCategoriesRouter)
  app.use(version + '/user', userRouter)
  app.use(version + '/cart', authenticateToken.authenticateToken, cartRouter)
  app.use(version + '/promo-codes', authenticateToken.authenticateToken, promoRouter)
  app.use(version + '/orders', authenticateToken.authenticateToken, ordersRouter)
  app.use(version + '/order-tracking', orderTrackingRouter)
  app.use(version + '/widgets', widgetsRouter)
  app.use(version + '/banners', bannersRouter)
  app.use(version + '/flash-sales', flashsalesRouter)
  app.use(version + '/contact', contactRouter)
  app.use(version + '/bank-info', bankInfoRouter)
  app.use(version + '/reviews', reviewsRouter)
  app.use(version + '/payment', paymentRouter)
  app.use(version + '/wishlist', authenticateToken.authenticateToken, wishlistRouter)
  app.use(version + '/chat', chatRouter)
}
