const productsRouter = require('./products.route')
const productCategoriesRouter = require('./product-category.route')
const userRouter = require('./user.route')
const cartRouter = require('./cart.route')
const promoRouter = require('./promo-codes.route')
const ordersRouter = require('./order.route')
const orderTrackingRouter = require('./order-tracking.route')
const widgetsRouter = require('./widgets.route')
const bannersRouter = require('./banners.route')
const aboutContentRouter = require('./aboutContent.route')
const termsContentRouter = require('./termsContent.route')
const cooperationContactContentRouter = require('./cooperationContactContent.route')
const homeWhyChooseUsContentRouter = require('./homeWhyChooseUsContent.route')
const blogRouter = require('./blog.route')
const blogCategoryRouter = require('./blog-category.route')
const blogTagsRouter = require('./blog-tags.route')
const gameNewsContentRouter = require('./gameNewsContent.route')
const vipContentRouter = require('./vipContent.route')
const flashsalesRouter = require('./flashsales.route')
const contactRouter = require('./contact.route')
const bankInfoRouter = require('./bankInfo.route')
const reviewsRouter = require('./reviews.route')
const paymentRouter = require('./payment.route')
const webhookRouter = require('./webhook.route')
const wishlistRouter = require('./wishlist.route')
const chatRouter = require('./chat.route')
const privacyPolicyPageRouter = require('./privacyPolicyPage.route')
const returnPolicyPageRouter = require('./returnPolicyPage.route')
const faqPageRouter = require('./faqPage.route')
const footerContentRouter = require('./footerContent.route')
const gameAccountContentRouter = require('./gameAccountContent.route')
const comingSoonContentRouter = require('./comingSoonContent.route')
const devPaymentRouter = require('./devPayment.route')

const authenticateToken = require('../../middlewares/client/authenticateToken.middleware')

module.exports = app => {
  const version = '/api/v1'
  app.use(version + '/products', productsRouter)
  app.use(version + '/product-categories', productCategoriesRouter)
  app.use(version + '/user', userRouter)
  app.use(version + '/cart', authenticateToken.authenticateToken, cartRouter)
  app.use(version + '/promo-codes', authenticateToken.authenticateToken, promoRouter)
  app.use(version + '/orders', authenticateToken.authenticateToken, ordersRouter)
  app.use(version + '/order-tracking', orderTrackingRouter)
  app.use(version + '/widgets', widgetsRouter)
  app.use(version + '/banners', bannersRouter)
  app.use(version + '/about', aboutContentRouter)
  app.use(version + '/terms', termsContentRouter)
  app.use(version + '/cooperation-contact', cooperationContactContentRouter)
  app.use(version + '/home-why-choose-us', homeWhyChooseUsContentRouter)
  app.use(version + '/blog', blogRouter)
  app.use(version + '/blog-posts', blogRouter)
  app.use(version + '/blog-categories', blogCategoryRouter)
  app.use(version + '/blog-tags', blogTagsRouter)
  app.use(version + '/game-news', gameNewsContentRouter)
  app.use(version + '/vip', vipContentRouter)
  app.use(version + '/flash-sales', flashsalesRouter)
  app.use(version + '/contact', contactRouter)
  app.use(version + '/bank-info', bankInfoRouter)
  app.use(version + '/reviews', reviewsRouter)
  app.use(version + '/payment', paymentRouter)
  app.use(version + '/webhooks', webhookRouter)
  app.use(version + '/wishlist', authenticateToken.authenticateToken, wishlistRouter)
  app.use(version + '/chat', chatRouter)
  app.use(version + '/privacy-policy', privacyPolicyPageRouter)
  app.use(version + '/return-policy', returnPolicyPageRouter)
  app.use(version + '/faq', faqPageRouter)
  app.use(version + '/footer', footerContentRouter)
  app.use(version + '/game-account', gameAccountContentRouter)
  app.use(version + '/coming-soon', comingSoonContentRouter)

  if (process.env.NODE_ENV !== 'production') {
    app.use(version + '/dev-payments', devPaymentRouter)
  }
}
