const systemConfig = require('../../../../config/system')
const dashboardRoutes = require('./system/dashboard.route')
const productsRoutes = require('./product/products.route')
const productContentAssistantRoutes = require('./product/productContentAssistant.route')
const productCredentialRoutes = require('./product/productCredentials.route')
const productCategoryRoutes = require('./product/productCategories.route')
const permissionsRoutes = require('./access/permissions.route')
const permissionGroupsRoutes = require('./access/permissionGroups.route')
const rolesRoutes = require('./access/roles.route')
const accountsRoutes = require('./access/adminAccounts.route')
const authRoutes = require('./access/auth.route')
const meRoutes = require('./access/me.route')
const adminWebsiteConfigRoutes = require('./system/websiteConfig.route')
const promoCodesRoutes = require('./commerce/promoCodes.route')
const ordersRoutes = require('./commerce/orders.route')
const purchaseReceiptRoutes = require('./commerce/purchaseReceipts.route')
const widgetsRoutes = require('./system/widgets.route')
const bannersRoutes = require('./system/banners.route')
const aboutContentRoutes = require('./cms/aboutContent.route')
const termsContentRoutes = require('./cms/termsContent.route')
const cooperationContactContentRoutes = require('./cms/cooperationContactContent.route')
const homeWhyChooseUsContentRoutes = require('./cms/homeWhyChooseUsContent.route')
const blogRoutes = require('./blog/blog.route')
const blogCategoryRoutes = require('./blog/blogCategory.route')
const blogTagRoutes = require('./blog/blogTag.route')
const blogAgentRoutes = require('./blog/blogAgent.route')
const blogPublishQueueRoutes = require('./blog/blogPublishQueue.route')
const cmsPageRoutes = require('./cms/cmsPage.route')
const cmsRevisionRoutes = require('./cms/cmsRevision.route')
const contentTranslationRoutes = require('./cms/contentTranslation.route')
const mediaLibraryRoutes = require('./system/mediaLibrary.route')
const gameNewsContentRoutes = require('./cms/gameNewsContent.route')
const vipContentRoutes = require('./cms/vipContent.route')
const flashSaleRoutes = require('./commerce/flashSales.route')
const bankInfoRoutes = require('./commerce/bankInfo.route')
const reviewsRoutes = require('./commerce/reviews.route')
const chatbotConfigRoutes = require('./chatbot/chatbotConfig.route')
const contactPageRoutes = require('./cms/contactPage.route')
const privacyPolicyPageRoutes = require('./cms/privacyPolicyPage.route')
const returnPolicyPageRoutes = require('./cms/returnPolicyPage.route')
const faqPageRoutes = require('./cms/faqPage.route')
const footerContentRoutes = require('./cms/footerContent.route')
const gameAccountContentRoutes = require('./cms/gameAccountContent.route')
const comingSoonContentRoutes = require('./cms/comingSoonContent.route')
const quickRepliesRoutes = require('./chatbot/quickReplies.route')
const quickReplyCategoriesRoutes = require('./chatbot/quickReplyCategories.route')

const authenticateToken = require('../../middlewares/admin/authenticateToken.middleware')

module.exports = app => {
  const PATH_ADMIN = systemConfig.prefixAdmin

  app.use(PATH_ADMIN + '/dashboard', authenticateToken.authenticateToken, dashboardRoutes)
  app.use(PATH_ADMIN + '/products', authenticateToken.authenticateToken, productsRoutes)
  app.use(PATH_ADMIN + '/product-content-assistant', authenticateToken.authenticateToken, productContentAssistantRoutes)
  app.use(PATH_ADMIN + '/product-credentials', authenticateToken.authenticateToken, productCredentialRoutes)
  app.use(PATH_ADMIN + '/product-categories', authenticateToken.authenticateToken, productCategoryRoutes)
  app.use(PATH_ADMIN + '/permissions', authenticateToken.authenticateToken, permissionsRoutes)
  app.use(PATH_ADMIN + '/permission-groups', authenticateToken.authenticateToken, permissionGroupsRoutes)
  app.use(PATH_ADMIN + '/roles', authenticateToken.authenticateToken, rolesRoutes)
  app.use(PATH_ADMIN + '/accounts', authenticateToken.authenticateToken, accountsRoutes)
  app.use(PATH_ADMIN + '/auth', authRoutes)
  app.use(PATH_ADMIN + '/me', authenticateToken.authenticateToken, meRoutes)
  app.use(PATH_ADMIN + '/website-config', adminWebsiteConfigRoutes)
  app.use(PATH_ADMIN + '/promo-codes', authenticateToken.authenticateToken, promoCodesRoutes)
  app.use(PATH_ADMIN + '/orders', authenticateToken.authenticateToken, ordersRoutes)
  app.use(PATH_ADMIN + '/purchase-receipts', authenticateToken.authenticateToken, purchaseReceiptRoutes)
  app.use(PATH_ADMIN + '/widgets', authenticateToken.authenticateToken, widgetsRoutes)
  app.use(PATH_ADMIN + '/banners', authenticateToken.authenticateToken, bannersRoutes)
  app.use(PATH_ADMIN + '/about', authenticateToken.authenticateToken, aboutContentRoutes)
  app.use(PATH_ADMIN + '/terms', authenticateToken.authenticateToken, termsContentRoutes)
  app.use(PATH_ADMIN + '/cooperation-contact', authenticateToken.authenticateToken, cooperationContactContentRoutes)
  app.use(PATH_ADMIN + '/home-why-choose-us', authenticateToken.authenticateToken, homeWhyChooseUsContentRoutes)
  app.use(PATH_ADMIN + '/blog', authenticateToken.authenticateToken, blogRoutes)
  app.use(PATH_ADMIN + '/blog-posts', authenticateToken.authenticateToken, blogRoutes)
  app.use(PATH_ADMIN + '/blog-categories', authenticateToken.authenticateToken, blogCategoryRoutes)
  app.use(PATH_ADMIN + '/blog-tags', authenticateToken.authenticateToken, blogTagRoutes)
  app.use(PATH_ADMIN + '/blog-agent', authenticateToken.authenticateToken, blogAgentRoutes)
  app.use(PATH_ADMIN + '/blog-publish-queue', authenticateToken.authenticateToken, blogPublishQueueRoutes)
  app.use(PATH_ADMIN + '/cms-pages', authenticateToken.authenticateToken, cmsPageRoutes)
  app.use(PATH_ADMIN + '/cms-revisions', authenticateToken.authenticateToken, cmsRevisionRoutes)
  app.use(PATH_ADMIN + '/content-translation', authenticateToken.authenticateToken, contentTranslationRoutes)
  app.use(PATH_ADMIN + '/media-library', authenticateToken.authenticateToken, mediaLibraryRoutes)
  app.use(PATH_ADMIN + '/game-news', authenticateToken.authenticateToken, gameNewsContentRoutes)
  app.use(PATH_ADMIN + '/vip', authenticateToken.authenticateToken, vipContentRoutes)
  app.use(PATH_ADMIN + '/flash-sales', authenticateToken.authenticateToken, flashSaleRoutes)
  app.use(PATH_ADMIN + '/bank-infos', authenticateToken.authenticateToken, bankInfoRoutes)
  app.use(PATH_ADMIN + '/reviews', authenticateToken.authenticateToken, reviewsRoutes)
  app.use(PATH_ADMIN + '/chatbot-config', authenticateToken.authenticateToken, chatbotConfigRoutes)
  app.use(PATH_ADMIN + '/contact-page', authenticateToken.authenticateToken, contactPageRoutes)
  app.use(PATH_ADMIN + '/privacy-policy', authenticateToken.authenticateToken, privacyPolicyPageRoutes)
  app.use(PATH_ADMIN + '/return-policy', authenticateToken.authenticateToken, returnPolicyPageRoutes)
  app.use(PATH_ADMIN + '/faq', authenticateToken.authenticateToken, faqPageRoutes)
  app.use(PATH_ADMIN + '/footer', authenticateToken.authenticateToken, footerContentRoutes)
  app.use(PATH_ADMIN + '/game-account', authenticateToken.authenticateToken, gameAccountContentRoutes)
  app.use(PATH_ADMIN + '/coming-soon', authenticateToken.authenticateToken, comingSoonContentRoutes)
  app.use(PATH_ADMIN + '/quick-replies', authenticateToken.authenticateToken, quickRepliesRoutes)
  app.use(PATH_ADMIN + '/quick-reply-categories', authenticateToken.authenticateToken, quickReplyCategoriesRoutes)
}











