const systemConfig = require('../../../../config/system')
const dashboardRoutes = require('./dashboard.route')
const productsRoutes = require('./product.route')
const productCredentialRoutes = require('./productCredential.route')
const productCategoryRoutes = require('./product-category.route')
const permissionsRoutes = require('./permission.route')
const permissionGroupsRoutes = require('./permission-groups.route')
const rolesRoutes = require('./roles.route')
const accountsRoutes = require('./adminAccounts.route')
const authRoutes = require('./auth.route')
const meRoutes = require('./me.route')
const adminWebsiteConfigRoutes = require('./adminWebsiteConfig.route')
const promoCodesRoutes = require('./promoCodes.route')
const ordersRoutes = require('./order.route')
const purchaseReceiptRoutes = require('./purchaseReceipt.route')
const widgetsRoutes = require('./widgets.route')
const bannersRoutes = require('./banners.route')
const aboutContentRoutes = require('./aboutContent.route')
const termsContentRoutes = require('./termsContent.route')
const cooperationContactContentRoutes = require('./cooperationContactContent.route')
const homeWhyChooseUsContentRoutes = require('./homeWhyChooseUsContent.route')
const blogRoutes = require('./blog.route')
const gameNewsContentRoutes = require('./gameNewsContent.route')
const vipContentRoutes = require('./vipContent.route')
const flashSaleRoutes = require('./flashSale.route')
const bankInfoRoutes = require('./bankInfo.route')
const reviewsRoutes = require('./reviews.route')
const chatbotConfigRoutes = require('./chatbotConfig.route')
const contactPageRoutes = require('./contactPage.route')
const privacyPolicyPageRoutes = require('./privacyPolicyPage.route')
const returnPolicyPageRoutes = require('./returnPolicyPage.route')
const faqPageRoutes = require('./faqPage.route')
const footerContentRoutes = require('./footerContent.route')
const gameAccountContentRoutes = require('./gameAccountContent.route')
const comingSoonContentRoutes = require('./comingSoonContent.route')
const quickRepliesRoutes = require('./quickReplies.route')
const quickReplyCategoriesRoutes = require('./quickReplyCategories.route')

const authenticateToken = require('../../middlewares/admin/authenticateToken.middleware')

module.exports = app => {
  const PATH_ADMIN = systemConfig.prefixAdmin

  app.use(PATH_ADMIN + '/dashboard', authenticateToken.authenticateToken, dashboardRoutes)
  app.use(PATH_ADMIN + '/products', authenticateToken.authenticateToken, productsRoutes)
  app.use(PATH_ADMIN + '/product-credentials', authenticateToken.authenticateToken, productCredentialRoutes)
  app.use(PATH_ADMIN + '/product-categories', authenticateToken.authenticateToken, productCategoryRoutes)
  app.use(PATH_ADMIN + '/permissions', authenticateToken.authenticateToken, permissionsRoutes)
  app.use(PATH_ADMIN + '/permission-groups', authenticateToken.authenticateToken, permissionGroupsRoutes)
  app.use(PATH_ADMIN + '/roles', authenticateToken.authenticateToken, rolesRoutes)
  app.use(PATH_ADMIN + '/accounts', authenticateToken.authenticateToken, accountsRoutes)
  app.use(PATH_ADMIN + '/auth', authRoutes)
  app.use(PATH_ADMIN + '/me', authenticateToken.authenticateToken, meRoutes)
  app.use(PATH_ADMIN + '/website-config', adminWebsiteConfigRoutes)
  app.use(PATH_ADMIN + '/promo-codes', authenticateToken.authenticateToken, promoCodesRoutes)
  app.use(PATH_ADMIN + '/orders', authenticateToken.authenticateToken, ordersRoutes)
  app.use(PATH_ADMIN + '/purchase-receipts', authenticateToken.authenticateToken, purchaseReceiptRoutes)
  app.use(PATH_ADMIN + '/widgets', authenticateToken.authenticateToken, widgetsRoutes)
  app.use(PATH_ADMIN + '/banners', authenticateToken.authenticateToken, bannersRoutes)
  app.use(PATH_ADMIN + '/about', authenticateToken.authenticateToken, aboutContentRoutes)
  app.use(PATH_ADMIN + '/terms', authenticateToken.authenticateToken, termsContentRoutes)
  app.use(PATH_ADMIN + '/cooperation-contact', authenticateToken.authenticateToken, cooperationContactContentRoutes)
  app.use(PATH_ADMIN + '/home-why-choose-us', authenticateToken.authenticateToken, homeWhyChooseUsContentRoutes)
  app.use(PATH_ADMIN + '/blog', authenticateToken.authenticateToken, blogRoutes)
  app.use(PATH_ADMIN + '/game-news', authenticateToken.authenticateToken, gameNewsContentRoutes)
  app.use(PATH_ADMIN + '/vip', authenticateToken.authenticateToken, vipContentRoutes)
  app.use(PATH_ADMIN + '/flash-sales', authenticateToken.authenticateToken, flashSaleRoutes)
  app.use(PATH_ADMIN + '/bank-infos', authenticateToken.authenticateToken, bankInfoRoutes)
  app.use(PATH_ADMIN + '/reviews', authenticateToken.authenticateToken, reviewsRoutes)
  app.use(PATH_ADMIN + '/chatbot-config', authenticateToken.authenticateToken, chatbotConfigRoutes)
  app.use(PATH_ADMIN + '/contact-page', authenticateToken.authenticateToken, contactPageRoutes)
  app.use(PATH_ADMIN + '/privacy-policy', authenticateToken.authenticateToken, privacyPolicyPageRoutes)
  app.use(PATH_ADMIN + '/return-policy', authenticateToken.authenticateToken, returnPolicyPageRoutes)
  app.use(PATH_ADMIN + '/faq', authenticateToken.authenticateToken, faqPageRoutes)
  app.use(PATH_ADMIN + '/footer', authenticateToken.authenticateToken, footerContentRoutes)
  app.use(PATH_ADMIN + '/game-account', authenticateToken.authenticateToken, gameAccountContentRoutes)
  app.use(PATH_ADMIN + '/coming-soon', authenticateToken.authenticateToken, comingSoonContentRoutes)
  app.use(PATH_ADMIN + '/quick-replies', authenticateToken.authenticateToken, quickRepliesRoutes)
  app.use(PATH_ADMIN + '/quick-reply-categories', authenticateToken.authenticateToken, quickReplyCategoriesRoutes)
}
