const systemConfig = require('../../../../config/system')
const dashboardRoutes = require('./dashboard.route')
const productsRoutes = require('./product.route')
const productCategoryRoutes = require('./product-category.route')
const permissionsRoutes = require('./permission.route')
const permissionGroupsRoutes = require('./permission-groups.route')
const rolesRoutes = require('./roles.route')
const accountsRoutes = require('./adminAccounts.route')
const authRoutes = require('./auth.route')
const meRoutes = require('./me.route')
const adminWebsiteConfigRoutes = require('./adminWebsiteConfig.route')
const promoCodesRoutes = require('./promoCodes.route')
const ordersRoutes = require('./order.route')
const widgetsRoutes = require('./widgets.route')
const bannersRoutes = require('./banners.route')
const flashSaleRoutes = require('./flashSale.route')
const bankInfoRoutes = require('./bankInfo.route')
const reviewsRoutes = require('./reviews.route')
const chatbotConfigRoutes = require('./chatbotConfig.route')

const authenticateToken = require('../../middlewares/admin/authenticateToken.middleware')

module.exports = app => {
  const PATH_ADMIN = systemConfig.prefixAdmin

  app.use(PATH_ADMIN + '/dashboard', authenticateToken.authenticateToken, dashboardRoutes)
  app.use(PATH_ADMIN + '/products', authenticateToken.authenticateToken, productsRoutes)
  app.use(PATH_ADMIN + '/product-categories', authenticateToken.authenticateToken, productCategoryRoutes)
  app.use(PATH_ADMIN + '/permissions', authenticateToken.authenticateToken, permissionsRoutes)
  app.use(PATH_ADMIN + '/permission-groups', authenticateToken.authenticateToken, permissionGroupsRoutes)
  app.use(PATH_ADMIN + '/roles', authenticateToken.authenticateToken, rolesRoutes)
  app.use(PATH_ADMIN + '/accounts', authenticateToken.authenticateToken, accountsRoutes)
  app.use(PATH_ADMIN + '/auth', authRoutes)
  app.use(PATH_ADMIN + '/me', authenticateToken.authenticateToken, meRoutes)
  app.use(PATH_ADMIN + '/website-config', adminWebsiteConfigRoutes)
  app.use(PATH_ADMIN + '/promo-codes', authenticateToken.authenticateToken, promoCodesRoutes)
  app.use(PATH_ADMIN + '/orders', authenticateToken.authenticateToken, ordersRoutes)
  app.use(PATH_ADMIN + '/widgets', authenticateToken.authenticateToken, widgetsRoutes)
  app.use(PATH_ADMIN + '/banners', authenticateToken.authenticateToken, bannersRoutes)
  app.use(PATH_ADMIN + '/flash-sales', authenticateToken.authenticateToken, flashSaleRoutes)
  app.use(PATH_ADMIN + '/bank-infos', authenticateToken.authenticateToken, bankInfoRoutes)
  app.use(PATH_ADMIN + '/reviews', authenticateToken.authenticateToken, reviewsRoutes)
  app.use(PATH_ADMIN + '/chatbot-config', authenticateToken.authenticateToken, chatbotConfigRoutes)
}
